### ISSUE TITLE
сделать выступления "оценка сроков и того хуже, тайм-трекинг"

### ISSUE THREAD

**Issue by sharovatov** [sharovatov/teamlead#11]

**Comment by sharovatov** [comment]
готовлюсь тут: https://github.com/sharovatov/teamlead/blob/master/talks/estimation_and_tracking.md

**Comment by Luchanso** [comment]
Огромное спасибо, задонатил немного 😉

**Comment by sharovatov** [comment]
ничего себе!!! увидел! спасибо огромное, это прямо мега-приятно! :)

**Comment by Luchanso** [comment]
Есть предположение, что нужно оценивать время задач (проектов), чтобы понимать, когда они затягиваются и может быть потрачено больше ресурсов, чем изначально потребуется.

**Comment by sharovatov** [comment]
спасибо, тоже добавлю и рассмотрю

**Comment by sharovatov** [comment]
https://www.youtube.com/watch?v=tqoJOEjeAEw&t=2s

**Comment by Luchanso** [comment]
Спасибо было интересно посмотреть, у меня есть на тему прогнозов [заметка](https://medium.com/swlh/why-engineers-cannot-estimate-time-5639750df419)
